name: flutter_breaking 
version: 1.0.0+1
environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.1
  cupertino_icons: ^1.0.4
  dio: ^4.0.4
  flutter_bloc: ^8.0.1
  flutter_offline: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/